version = 5.7.0
archive_dir = /etc/letsencrypt/archive/lebaladna.app
cert = /etc/letsencrypt/live/lebaladna.app/cert.pem
privkey = /etc/letsencrypt/live/lebaladna.app/privkey.pem
chain = /etc/letsencrypt/live/lebaladna.app/chain.pem
fullchain = /etc/letsencrypt/live/lebaladna.app/fullchain.pem
[renewalparams]
account = 85ff9ff45bfe36ed3baa7a2eec48cf20
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
lebaladna.app = /var/www/certbot
www.lebaladna.app = /var/www/certbot
